// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/notification_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i12;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i13;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i15;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i17;
import 'package:flutter_local_notifications/src/types.dart' as _i18;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/controllers/occurrences_manager.dart' as _i7;
import 'package:mona/data/model/medication_schedule.dart' as _i4;
import 'package:mona/data/model/molecule.dart' as _i11;
import 'package:mona/data/model/scheduled_occurrence.dart' as _i8;
import 'package:mona/data/model/units.dart' as _i10;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i3;
import 'package:mona/services/preferences_service.dart' as _i9;
import 'package:mona/services/repository.dart' as _i2;
import 'package:timezone/timezone.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i3.MedicationScheduleProvider {
  @override
  _i2.Repository<_i4.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i4.MedicationSchedule>);

  @override
  List<_i4.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i4.MedicationSchedule>[],
        returnValueForMissingStub: <_i4.MedicationSchedule>[],
      ) as List<_i4.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.MedicationSchedule? getScheduleById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MedicationSchedule?);

  @override
  _i5.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i4.MedicationSchedule? schedule) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OccurrencesManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccurrencesManager extends _i1.Mock
    implements _i7.OccurrencesManager {
  @override
  List<_i8.ScheduledOccurrence> currentFor(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentFor,
          [schedule],
        ),
        returnValue: <_i8.ScheduledOccurrence>[],
        returnValueForMissingStub: <_i8.ScheduledOccurrence>[],
      ) as List<_i8.ScheduledOccurrence>);

  @override
  List<_i8.ScheduledOccurrence> upcomingFor(
    _i4.MedicationSchedule? schedule, {
    required int? days,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upcomingFor,
          [schedule],
          {#days: days},
        ),
        returnValue: <_i8.ScheduledOccurrence>[],
        returnValueForMissingStub: <_i8.ScheduledOccurrence>[],
      ) as List<_i8.ScheduledOccurrence>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i9.PreferencesService {
  @override
  bool get autoCheckUpdatesEnabled => (super.noSuchMethod(
        Invocation.getter(#autoCheckUpdatesEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Units get units => (super.noSuchMethod(
        Invocation.getter(#units),
        returnValue: _i10.Units.pg_mL_ng_dL,
        returnValueForMissingStub: _i10.Units.pg_mL_ng_dL,
      ) as _i10.Units);

  @override
  List<_i11.Molecule> get customMolecules => (super.noSuchMethod(
        Invocation.getter(#customMolecules),
        returnValue: <_i11.Molecule>[],
        returnValueForMissingStub: <_i11.Molecule>[],
      ) as List<_i11.Molecule>);

  @override
  List<_i11.Molecule> get allMolecules => (super.noSuchMethod(
        Invocation.getter(#allMolecules),
        returnValue: <_i11.Molecule>[],
        returnValueForMissingStub: <_i11.Molecule>[],
      ) as List<_i11.Molecule>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> setAutoCheckUpdatesEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoCheckUpdatesEnabled,
          [isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotificationsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSavedLanguageTag(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setSavedLanguageTag,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setUnits(_i10.Units? units) => (super.noSuchMethod(
        Invocation.method(
          #setUnits,
          [units],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCustomMolecule(_i11.Molecule? molecule) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomMolecule,
          [molecule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCustomMolecule(String? name) => (super.noSuchMethod(
        Invocation.method(
          #removeCustomMolecule,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i12.FlutterLocalNotificationsPlugin {
  @override
  _i5.Future<bool?> initialize({
    required _i13.InitializationSettings? settings,
    _i14.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i14.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #settings: settings,
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i5.Future<bool?>.value(),
        returnValueForMissingStub: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<_i14.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i5.Future<_i14.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i5.Future<_i14.NotificationAppLaunchDetails?>.value(),
          ) as _i5.Future<_i14.NotificationAppLaunchDetails?>);

  @override
  _i5.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i15.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #notificationDetails: notificationDetails,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel({
    required int? id,
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #id: id,
            #tag: tag,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> zonedSchedule({
    required int? id,
    required _i16.TZDateTime? scheduledDate,
    required _i15.NotificationDetails? notificationDetails,
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i18.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [],
          {
            #id: id,
            #scheduledDate: scheduledDate,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShow({
    required int? id,
    required _i14.RepeatInterval? repeatInterval,
    required _i15.NotificationDetails? notificationDetails,
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [],
          {
            #id: id,
            #repeatInterval: repeatInterval,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i15.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i17.AndroidScheduleMode? androidScheduleMode =
        _i17.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [],
          {
            #id: id,
            #repeatDurationInterval: repeatDurationInterval,
            #notificationDetails: notificationDetails,
            #title: title,
            #body: body,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i14.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i5.Future<List<_i14.PendingNotificationRequest>>.value(
                    <_i14.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i5.Future<List<_i14.PendingNotificationRequest>>.value(
                    <_i14.PendingNotificationRequest>[]),
          ) as _i5.Future<List<_i14.PendingNotificationRequest>>);

  @override
  _i5.Future<List<_i14.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i14.ActiveNotification>>.value(
            <_i14.ActiveNotification>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i14.ActiveNotification>>.value(
                <_i14.ActiveNotification>[]),
      ) as _i5.Future<List<_i14.ActiveNotification>>);
}
